.PHONY : all clean

SRCS=$(wildcard *.F90)
OBJS=$(SRCS:.F90=.o)
FC=gfortran

BLOCKSIZE=32
DOOPT = 1
DOREORD = 0
PROFILE = 0

F90FLAGS := -O2 -ffree-line-length-none

EXE=GearProc.exe

F90FLAGS := $(F90FLAGS) -DDOREORD=$(DOREORD) -DBLOCKSIZE=$(BLOCKSIZE)
all: $(OBJS) $(EXE)

%.o : %.F90
	$(FC) $(F90FLAGS) -c $<

$(EXE): $(OBJS)
	$(FC) $(F90FLAGS) $(PFUNIT_LFLAGS) -o $@ $(OBJS)
clean:
	rm -f *.o *.mod *.x *.exe
